# .repo.toml

[about]
description = "Install software from the Free Law Project with brew/homebrew"
# topics = []
license = "GPL-2.0-only"

[urls]
git_ssh = "git@github.com:fini-net/template-repo.git"
web_url = "https://github.com/fini-net/template-repo"

[flags]
claude = true
claude-review = true
copilot-review = true
